# Generated by Django 4.1.2 on 2022-11-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=220)),
                ('doc_spec', models.CharField(max_length=300)),
                ('doc_image', models.ImageField(upload_to='doctors')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='dept_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dot_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pat_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
