# Generated by Django 4.1.2 on 2022-11-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_doctors_alter_booking_dept_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=220)),
                ('dep_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='ph_no',
            field=models.CharField(max_length=10),
        ),
    ]
