# Generated by Django 4.1.2 on 2022-12-02 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_department_alter_booking_ph_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], max_length=220),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.department'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_spec',
            field=models.CharField(max_length=225),
        ),
    ]
